# Generated by Django 5.1.2 on 2024-11-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='score',
            field=models.IntegerField(default=5),
        ),
    ]
