# Generated by Django 5.1.2 on 2024-12-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="ahort_descritpion",
            new_name="short_descritpion",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
