# Generated by Django 5.1.2 on 2024-10-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clase_comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scoore', models.IntegerField(default=3)),
                ('comentario', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
