# Generated by Django 5.1.2 on 2024-10-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase_comentario',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
