# Generated by Django 5.1.2 on 2024-10-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_clase_comentario_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase_comentario',
            name='signature',
            field=models.CharField(default='firma', max_length=100),
        ),
    ]
