# Generated by Django 5.1.2 on 2024-11-08 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='apellido',
        ),
    ]
